# Generated by Django 5.2.6 on 2025-11-07 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='imagem',
            field=models.FileField(blank=True, default=None, null=True, upload_to='imagens/produto', verbose_name='Imagem de Produto'),
        ),
    ]
